# Tensorflow-2.x 

<img src="https://i.ytimg.com/vi/yjprpOoH5c8/maxresdefault.jpg" width="600" 
     height="300">

> TensorFlow is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices.
> Originally developed by researchers and engineers from the Google Brain team within Google’s AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains.

<img src="https://www.imaginarycloud.com/blog/content/images/2021/04/pytorchvs_cover.png" width="600" 
     height="300">

TensorFlow is a popular and widely used open-source machine learning framework developed by Google. It offers a range of features and benefits that make it a powerful tool for building and deploying machine learning models. Here are some reasons why TensorFlow is commonly used:

- Flexibility: TensorFlow provides a flexible and modular architecture that allows developers to build and customize machine learning models for a wide variety of tasks. It supports both high-level and low-level APIs, giving users the flexibility to work at different levels of abstraction.

- Scalability: TensorFlow is designed to handle large-scale machine learning projects. It enables efficient distributed computing across multiple CPUs and GPUs, making it suitable for training models on large datasets.

- Wide range of applications: TensorFlow can be used for a diverse range of machine learning tasks, including image and speech recognition, natural language processing, recommendation systems, and more. It supports various neural network architectures, such as convolutional neural networks (CNNs), recurrent neural networks (RNNs), and transformers.

- Community and ecosystem: TensorFlow has a large and active community of developers, researchers, and enthusiasts. This community contributes to the development of the framework by sharing code, providing support, and creating libraries and tools that extend TensorFlow's functionality. This vibrant ecosystem makes it easier to find resources, tutorials, and pre-trained models.

- Visualization and debugging: TensorFlow includes tools for visualizing and debugging models, which can aid in understanding the behavior of the model during training and inference. It provides built-in support for TensorBoard, a web-based tool for visualizing metrics, model graphs, and other aspects of the training process.

- Deployment options: TensorFlow offers multiple deployment options, allowing models to be deployed in a variety of environments. It supports deployment on different platforms, including desktops, servers, mobile devices, and even specialized hardware such as Google's Tensor Processing Units (TPUs).

- Integration with other libraries and frameworks: TensorFlow can be easily integrated with other popular libraries and frameworks in the Python ecosystem, such as NumPy, Pandas, and scikit-learn. This enables seamless data manipulation, preprocessing, and post-processing tasks in conjunction with TensorFlow's capabilities.

- Continued development and support: TensorFlow is actively developed and maintained by Google and the TensorFlow community. Regular updates and improvements ensure that the framework stays up to date with the latest advancements in machine learning research and industry practices.

These are just a few reasons why TensorFlow is a popular choice for machine learning tasks. However, it's worth noting that the choice of framework ultimately depends on the specific requirements and preferences of the user.

### For installing latest version of Tensorflow

> **pip install tensorflow**

> To run from Anaconda Prompt

> **!pip install tensorflow**

> To run from Jupyter Notebook

[Tensorflow Documentation](https://www.tensorflow.org/install)

- scalar is a single number.
- vector is an ordered collection of numbers with magnitude and direction.
- tensor is a multidimensional array that generalizes both scalars and vectors.

# 1. Tensors 

In [1]:
import tensorflow as tf

#create a 3x3 tensor filled with zeros

tensor_zeros = tf.zeros([3,3])
print(tensor_zeros)


tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [2]:
#Create a 2x2 tesnor filled with random values

tensor_random = tf.random.uniform([2,2])
print(tensor_random)

tf.Tensor(
[[0.71436405 0.30535758]
 [0.16557467 0.82902265]], shape=(2, 2), dtype=float32)


# 2. Automatic Differentiation 

In [3]:
# Define a variable
x = tf.Variable(2.0)

# Define a Computation

with tf.GradientTape() as tape:
    y = x ** 2
    
# compute gradients 

grad = tape.gradient(y,x)
print(grad)

tf.Tensor(4.0, shape=(), dtype=float32)


# 3. Neural Network 

In [4]:
# Define a simple neural network using TensorFlow's high-level Keras API
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_shape=(10,), activation='relu'),  # Dense layer with ReLU activation
    tf.keras.layers.Dense(1)  # Output layer
])

# Compile the model
model.compile(optimizer='adam', loss='mse')  # Using Adam optimizer and Mean Squared Error loss

# Generate random input
input_data = tf.random.uniform((1, 10))

# Forward pass
output = model(input_data)
print(output)




tf.Tensor([[-0.2500045]], shape=(1, 1), dtype=float32)


#### Flatten: Reshapes input into a one-dimensional array, often used to transition from convolutional layers to fully connected layers.

##### Dropout: Randomly sets a fraction of input units to zero during training to prevent overfitting by forcing the network to learn more robust features.

#### Dense: Fully connected layer where each input node is connected to each output node, performing a learned linear transformation followed by an activation function.