In [7]:
import numpy as np

# Broadcasting

In [8]:
arr = np.zeros((5,5))

In [9]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
row = np.array([7,8,9,4,6])

In [11]:
row

array([7, 8, 9, 4, 6])

In [12]:
arr.shape

(5, 5)

In [13]:
row.shape

(5,)

In [14]:
arr + row

array([[7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.],
       [7., 8., 9., 4., 6.]])

In [17]:
column = np.array([[1,3,4,6,2]])

In [18]:
column.shape

(1, 5)

In [19]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
column.T + arr

array([[1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2.]])

# Array Manipulation

In [23]:
arr1 = np.random.randint(1,20,(4,5))

In [24]:
arr1

array([[14,  3, 18, 16, 14],
       [ 5,  8, 10,  9, 13],
       [10,  8, 15, 15,  7],
       [17, 13,  7,  8, 18]])

In [25]:
arr1.shape

(4, 5)

In [26]:
arr1.size

20

In [31]:
arr1.reshape(10,2)

array([[14,  3],
       [18, 16],
       [14,  5],
       [ 8, 10],
       [ 9, 13],
       [10,  8],
       [15, 15],
       [ 7, 17],
       [13,  7],
       [ 8, 18]])

In [33]:
arr1.transpose()

array([[14,  5, 10, 17],
       [ 3,  8,  8, 13],
       [18, 10, 15,  7],
       [16,  9, 15,  8],
       [14, 13,  7, 18]])

In [35]:
arr1.T

array([[14,  5, 10, 17],
       [ 3,  8,  8, 13],
       [18, 10, 15,  7],
       [16,  9, 15,  8],
       [14, 13,  7, 18]])

In [37]:
s = arr1.flatten()

In [38]:
s.shape

(20,)

In [39]:
s

array([14,  3, 18, 16, 14,  5,  8, 10,  9, 13, 10,  8, 15, 15,  7, 17, 13,
        7,  8, 18])

In [40]:
arr2 = np.array([1,2,4,4,5])

In [42]:
arr2.ndim

1

In [44]:
np.expand_dims(arr2, axis=1)

array([[1],
       [2],
       [4],
       [4],
       [5]])

In [47]:
m = np.expand_dims(arr2, axis=0)

In [46]:
arr2.shape

(5,)

In [48]:
m.shape

(1, 5)

In [49]:
mat = np.array([[2],[5],[6]])

In [50]:
mat

array([[2],
       [5],
       [6]])

In [51]:
mat.shape

(3, 1)

In [52]:
mat.squeeze()

array([2, 5, 6])

In [54]:
sq = np.squeeze(mat)

In [55]:
sq.shape

(3,)

In [57]:
arr2

array([1, 2, 4, 4, 5])

In [58]:
np.repeat(arr2,3)

array([1, 1, 1, 2, 2, 2, 4, 4, 4, 4, 4, 4, 5, 5, 5])

In [61]:
np.diagonal(arr)

array([0., 0., 0., 0., 0.])

In [65]:
arr3 = np.array([1,5,6,8,7])

In [66]:
np.diag(arr3)

array([[1, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 7]])

# Binary Operation

In [79]:
arr1 = np.random.randint(1,10,(4,3))
arr2 = np.random.randint(1,10,(3,4))

In [69]:
arr1

array([[1, 1, 5],
       [1, 5, 7],
       [8, 1, 8],
       [8, 7, 5]])

In [70]:
arr2

array([[6, 4, 3],
       [6, 8, 1],
       [4, 9, 5],
       [6, 6, 2]])

In [71]:
arr1 & arr2

array([[0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 6, 0]], dtype=int32)

In [73]:
arr1 | arr2

array([[ 7,  5,  7],
       [ 7, 13,  7],
       [12,  9, 13],
       [14,  7,  7]], dtype=int32)

In [74]:
~arr2

array([[ -7,  -5,  -4],
       [ -7,  -9,  -2],
       [ -5, -10,  -6],
       [ -7,  -7,  -3]], dtype=int32)

In [75]:
arr1 * arr2

array([[ 6,  4, 15],
       [ 6, 40,  7],
       [32,  9, 40],
       [48, 42, 10]])

In [76]:
arr1 + arr2

array([[ 7,  5,  8],
       [ 7, 13,  8],
       [12, 10, 13],
       [14, 13,  7]])

In [77]:
arr1 - arr2

array([[-5, -3,  2],
       [-5, -3,  6],
       [ 4, -8,  3],
       [ 2,  1,  3]])

In [80]:
arr1@arr2

array([[117,  71,  82, 108],
       [ 62,  52,  51,  54],
       [ 58,  67,  52,  54],
       [105, 104,  82, 106]])

# Numpy String Function

In [82]:
arr = np.array(['datascience','machinelearning'])

In [83]:
arr

array(['datascience', 'machinelearning'], dtype='<U15')

In [85]:
np.char.upper(arr)

array(['DATASCIENCE', 'MACHINELEARNING'], dtype='<U15')

In [86]:
np.char.title(arr)

array(['Datascience', 'Machinelearning'], dtype='<U15')

In [87]:
np.char.split(arr)

array([list(['datascience']), list(['machinelearning'])], dtype=object)

# Mathematical Functions

In [88]:
arr1

array([[1, 8, 7],
       [2, 5, 2],
       [5, 3, 2],
       [8, 3, 7]])

In [89]:
np.sin(arr1)

array([[ 0.84147098,  0.98935825,  0.6569866 ],
       [ 0.90929743, -0.95892427,  0.90929743],
       [-0.95892427,  0.14112001,  0.90929743],
       [ 0.98935825,  0.14112001,  0.6569866 ]])

In [90]:
np.cos(arr1)

array([[ 0.54030231, -0.14550003,  0.75390225],
       [-0.41614684,  0.28366219, -0.41614684],
       [ 0.28366219, -0.9899925 , -0.41614684],
       [-0.14550003, -0.9899925 ,  0.75390225]])

In [91]:
np.tan(arr1)

array([[ 1.55740772, -6.79971146,  0.87144798],
       [-2.18503986, -3.38051501, -2.18503986],
       [-3.38051501, -0.14254654, -2.18503986],
       [-6.79971146, -0.14254654,  0.87144798]])

In [92]:
np.tanh(arr1)

array([[0.76159416, 0.99999977, 0.99999834],
       [0.96402758, 0.9999092 , 0.96402758],
       [0.9999092 , 0.99505475, 0.96402758],
       [0.99999977, 0.99505475, 0.99999834]])

In [94]:
np.log10(arr1)

array([[0.        , 0.90308999, 0.84509804],
       [0.30103   , 0.69897   , 0.30103   ],
       [0.69897   , 0.47712125, 0.30103   ],
       [0.90308999, 0.47712125, 0.84509804]])

In [95]:
np.sqrt(arr1)

array([[1.        , 2.82842712, 2.64575131],
       [1.41421356, 2.23606798, 1.41421356],
       [2.23606798, 1.73205081, 1.41421356],
       [2.82842712, 1.73205081, 2.64575131]])

In [97]:
np.power(arr1,2)

array([[ 1, 64, 49],
       [ 4, 25,  4],
       [25,  9,  4],
       [64,  9, 49]], dtype=int32)

In [98]:
np.mean(arr1)

4.416666666666667

In [99]:
np.median(arr1)

4.0

In [100]:
np.std(arr1)

2.465033242958173

In [101]:
np.var(arr1)

6.076388888888888

In [102]:
np.max(arr1)

8

In [103]:
np.min(arr1)

1

# Linear Algebra 

In [104]:
arr1

array([[1, 8, 7],
       [2, 5, 2],
       [5, 3, 2],
       [8, 3, 7]])

In [105]:
arr2

array([[4, 9, 5, 4],
       [8, 6, 7, 6],
       [7, 2, 3, 8]])

In [107]:
arr1@arr2

array([[117,  71,  82, 108],
       [ 62,  52,  51,  54],
       [ 58,  67,  52,  54],
       [105, 104,  82, 106]])

In [108]:
np.dot(arr1, arr2)

array([[117,  71,  82, 108],
       [ 62,  52,  51,  54],
       [ 58,  67,  52,  54],
       [105, 104,  82, 106]])

In [109]:
arr1

array([[1, 8, 7],
       [2, 5, 2],
       [5, 3, 2],
       [8, 3, 7]])

In [111]:
arr1 = np.random.randint(1,4,(4,4))

In [113]:
arr1

array([[2, 1, 1, 3],
       [1, 3, 2, 3],
       [1, 3, 2, 1],
       [3, 1, 1, 1]])

In [112]:
np.linalg.inv(arr1)

array([[-1. ,  1. , -1. ,  1. ],
       [-5. ,  5.5, -4.5,  3. ],
       [ 8. , -9. ,  8. , -5. ],
       [-0. ,  0.5, -0.5, -0. ]])

In [114]:
np.linalg.det(arr1)

-2.0000000000000004

In [115]:
matrix = np.matrix([[1,2],[4,5]])

In [116]:
matrix

matrix([[1, 2],
        [4, 5]])

In [117]:
np.linalg.det(matrix)

-2.9999999999999996

In [118]:
# Solve a sytem linear equations Ax=b
A = np.array([[2,1],[1,-3]])
B = np.array([8,-3])

In [119]:
equation = np.linalg.solve(A,B)

In [120]:
equation

array([3., 2.])

# Sort and Searching

In [121]:
arr = np.array([4,5,6,8,45,45,78,12,3,5,8])

In [122]:
arr

array([ 4,  5,  6,  8, 45, 45, 78, 12,  3,  5,  8])

In [123]:
np.sort(arr)

array([ 3,  4,  5,  5,  6,  8,  8, 12, 45, 45, 78])

In [127]:
np.searchsorted(arr,45)

4

In [130]:
np.where(arr>8)

(array([4, 5, 6, 7], dtype=int64),)

In [132]:
np.extract(arr>8 , arr)

array([45, 45, 78, 12])