In [1]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression , Ridge , Lasso , ElasticNet
from sklearn.metrics import mean_squared_error , r2_score

# Generate synthetic data

In [2]:
X, y = make_regression( n_samples=100 , n_features=10 , noise=0.1 , random_state=42)

# Split the data into training and test data

In [3]:
X_train , X_test, y_train, y_test = train_test_split(X, y , test_size=0.2 , random_state=42)

In [5]:
X_train.shape

(80, 10)

In [7]:
X_train

array([[-5.73662007e-01,  1.50399299e+00, -2.54977217e-01,
        -3.27532702e-02,  1.06430228e-01, -5.43424771e-01,
         1.09150685e+00, -5.46858941e-01, -7.12845783e-01,
        -2.65096981e+00],
       [ 2.06074792e+00,  6.86051460e-01, -9.64923461e-01,
        -2.48964148e-01,  1.36863156e+00,  9.71570951e-01,
        -1.75873949e+00,  1.75534084e+00,  6.45375950e-01,
         1.05842449e+00],
       [ 2.52693243e+00, -3.59292091e-01,  5.83928185e-01,
        -4.89439443e-01,  1.84670733e+00,  1.04416088e+00,
         1.10870358e+00, -5.30868773e-01,  6.81891490e-01,
         5.90654831e-01],
       [ 8.65897875e-02, -4.32558188e-01, -4.87606224e-01,
         1.16778206e+00, -4.11876966e-01,  2.54420843e-01,
        -4.20984481e-01, -1.55677235e-01,  3.37602662e-01,
         3.94452142e-01],
       [ 7.21672064e-01, -3.74820808e-01, -2.40325398e-01,
        -5.24520266e-01,  7.12998430e-01,  4.89374561e-01,
         4.44263311e-01, -1.12905177e+00, -1.22212781e+00,
         7.

In [6]:
X_test

array([[-1.26088395, -0.70766947,  1.26691115,  2.1221562 , -0.48423407,
         1.03246526,  0.77463405,  0.91786195, -1.51936997,  0.44381943],
       [-0.60170661, -1.95967012,  0.2088636 , -0.01349722, -1.22084365,
        -1.05771093,  0.19686124,  1.85227818,  0.82254491, -1.32818605],
       [-0.2750517 ,  0.31125015,  0.57655696, -1.51519106, -0.24903604,
         1.36687427,  1.11957491, -2.30192116,  1.64496771,  3.07888081],
       [ 0.33849641, -0.84984437, -0.4593609 ,  0.63278187,  0.24822059,
         2.27069286, -0.85608383, -0.41528791,  0.18186626,  0.83033582],
       [-0.88951443,  1.45353408,  0.01300189, -0.07710171,  0.82718325,
         0.34115197,  2.72016917, -0.81581028,  0.2766908 , -0.26465683],
       [ 0.82048218,  0.14671369, -0.16711808,  1.06667469,  0.64870989,
         1.16929559, -0.81693567,  0.50727403,  1.38215899,  1.20650897],
       [-0.12791759, -1.081548  , -0.64657288, -1.60644632, -1.42225371,
         0.20346364,  0.88163976, -0.95554044

# Linear Regression 

In [8]:
linear_reg = LinearRegression()

In [9]:
linear_reg.fit(X_train , y_train)

LinearRegression()

In [10]:
y_pred_test = linear_reg.predict(X_test)

In [11]:
y_pred_test

array([ 213.48835456, -360.05021662,  289.01510218,  161.78655153,
        370.92360403,  256.14431586, -101.00348811,  238.84416273,
       -250.833725  , -501.18785991,  159.30802519, -123.29680963,
         77.64119013,  -12.80354995, -109.86385852, -183.49413058,
        134.56789458,  140.14184295, -366.04082479,  256.06968691])

In [12]:
y_test

array([ 213.39745784, -360.06583541,  289.03160226,  161.71911123,
        371.19550275,  256.10028821, -101.08381937,  238.84702346,
       -250.93173853, -501.1222001 ,  159.42010248, -123.30040133,
         77.53583081,  -12.74388703, -109.89166363, -183.60242364,
        134.61907222,  139.91519032, -366.07316356,  256.10081584])

In [13]:
linear_reg_mse = mean_squared_error(y_test , y_pred_test)
linear_reg_r2 = r2_score(y_test, y_pred_test)
print(linear_reg_mse)
print(linear_reg_r2)

0.010265673458293307
0.9999998282331861


# Ridge Regression

In [15]:
ridge_reg = Ridge(alpha=0.1)
ridge_reg.fit(X_train, y_train)
y_rig_pred = ridge_reg.predict(X_test)
ridge_reg_mse = mean_squared_error(y_test, y_rig_pred)
ridge_r2 = r2_score(y_test, y_rig_pred)
print(ridge_reg_mse)
print(ridge_r2)

0.1447719066127277
0.9999975776543794


# Lasso Regression

In [17]:
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X_train, y_train)
lasso_reg_predictions = lasso_reg.predict(X_test)
lasso_reg_mse = mean_squared_error(y_test, lasso_reg_predictions)
lasso_reg_r2 = r2_score(y_test, lasso_reg_predictions)
print(lasso_reg_mse)
print(lasso_reg_r2)

0.18237823772607173
0.9999969484195118


# Elastic Net Regression

In [19]:
elastic_net_reg = ElasticNet(alpha=0.1, l1_ratio=0.5)
elastic_net_reg.fit(X_train, y_train)
elastic_net_reg_predictions = elastic_net_reg.predict(X_test)
elastic_net_reg_mse = mean_squared_error(y_test, elastic_net_reg_predictions)
elastic_net_reg_r2 = r2_score(y_test, elastic_net_reg_predictions)
print(elastic_net_reg_mse)
print(elastic_net_reg_r2)

176.02832750565068
0.9970546671780763
